// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVeMgKYqyut9cl1o5I0ZVeUUqJmqlMB-s',
    appId: '1:949162768947:web:aa94f79a4914a019f18146',
    messagingSenderId: '949162768947',
    projectId: 'todotaskapp-83f3c',
    authDomain: 'todotaskapp-83f3c.firebaseapp.com',
    storageBucket: 'todotaskapp-83f3c.appspot.com',
    measurementId: 'G-291S1NEXET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEWYVoHtIleOtH34Hvx3mfOTGtIUFPhA0',
    appId: '1:949162768947:android:be24b1d792b50ad1f18146',
    messagingSenderId: '949162768947',
    projectId: 'todotaskapp-83f3c',
    storageBucket: 'todotaskapp-83f3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzoRTlOcoMv71mgjF5Y5uAjGrOEwMva30',
    appId: '1:949162768947:ios:0f5eae4e7f1478b5f18146',
    messagingSenderId: '949162768947',
    projectId: 'todotaskapp-83f3c',
    storageBucket: 'todotaskapp-83f3c.appspot.com',
    iosBundleId: 'com.example.todotaskapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzoRTlOcoMv71mgjF5Y5uAjGrOEwMva30',
    appId: '1:949162768947:ios:0f5eae4e7f1478b5f18146',
    messagingSenderId: '949162768947',
    projectId: 'todotaskapp-83f3c',
    storageBucket: 'todotaskapp-83f3c.appspot.com',
    iosBundleId: 'com.example.todotaskapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVeMgKYqyut9cl1o5I0ZVeUUqJmqlMB-s',
    appId: '1:949162768947:web:b10b6dee90aa5ad5f18146',
    messagingSenderId: '949162768947',
    projectId: 'todotaskapp-83f3c',
    authDomain: 'todotaskapp-83f3c.firebaseapp.com',
    storageBucket: 'todotaskapp-83f3c.appspot.com',
    measurementId: 'G-TYXNQ2MDPP',
  );
}
